---
name: Release binary

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    name: Build and upload binary package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: amd64
            os: linux
          - arch: arm64
            os: linux
          - arch: amd64
            os: darwin
          - arch: arm64
            os: darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.2"

      - name: Build Binary
        run: |
          go build -o vmalert-cli-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false

      - name: Upload release assets
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./vmalert-cli-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: vmalertcli-${{ matrix.os }}-${{ matrix.arch }}-latest
          tag: ${{ github.ref }}
