name: Release

# on:
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+*"
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5" # The Go version to download (if necessary) and use.
      - name: Generate
        uses: skx/github-action-build@master
        with:
          builder: .github/build
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: "*.amd64.bin"
